# Generated by Django 4.0.4 on 2022-05-31 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_name', models.CharField(max_length=20)),
                ('active', models.BooleanField()),
                ('period_0', models.CharField(max_length=20)),
                ('period_1', models.CharField(max_length=20)),
                ('period_2', models.CharField(max_length=20)),
                ('period_3', models.CharField(max_length=20)),
                ('period_4', models.CharField(max_length=20)),
                ('period_5', models.CharField(max_length=20)),
                ('period_6', models.CharField(max_length=20)),
                ('period_7', models.CharField(max_length=20)),
                ('period_8', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=20)),
                ('last', models.CharField(max_length=20)),
                ('student_id', models.CharField(max_length=10)),
                ('period', models.CharField(max_length=1)),
                ('exception', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_waitlist', to='attendance.student')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_record', to='attendance.student')),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_out', models.DateTimeField()),
                ('time_back', models.DateTimeField()),
                ('minutes', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_bathroom', to='attendance.student')),
            ],
        ),
    ]
