# Generated by Django 4.0.4 on 2022-06-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exception',
            field=models.BooleanField(),
        ),
    ]
