# Generated by Django 4.0.6 on 2022-07-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_student_exception'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aprPass',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='augPass',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='decPass',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='febPass',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='janPass',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='marPass',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mayPass',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='novPass',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='octPass',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sepPass',
            field=models.BooleanField(default=True),
        ),
    ]
