# Generated by Django 4.0.6 on 2022-07-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_student_aprpass_student_augpass_student_decpass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='julPass',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='junPass',
            field=models.BooleanField(default=True),
        ),
    ]
