# Generated by Django 4.0.4 on 2022-05-31 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_record_student_alter_record_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_name', models.CharField(max_length=20)),
                ('active', models.BooleanField()),
                ('period_0', models.CharField(max_length=20)),
                ('period_1', models.CharField(max_length=20)),
                ('period_2', models.CharField(max_length=20)),
                ('period_3', models.CharField(max_length=20)),
                ('period_4', models.CharField(max_length=20)),
                ('period_5', models.CharField(max_length=20)),
                ('period_6', models.CharField(max_length=20)),
                ('period_7', models.CharField(max_length=20)),
                ('period_8', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='exception',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_waitlist', to='attendance.student')),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_out', models.DateTimeField()),
                ('time_back', models.DateTimeField()),
                ('minutes', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_bathroom', to='attendance.student')),
            ],
        ),
    ]
