# Generated by Django 4.0.4 on 2022-05-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_student_exception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exception',
            field=models.BooleanField(),
        ),
    ]
