# Generated by Django 4.1.1 on 2022-09-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_student_absent_student_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='reason',
            field=models.CharField(max_length=200),
        ),
    ]
