# Generated by Django 4.0.4 on 2022-05-23 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_student_exception'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='exception',
        ),
    ]
