# Generated by Django 4.0.4 on 2022-05-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_waitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
