# Generated by Django 4.1.1 on 2022-09-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_incident_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='reason',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reason',
            field=models.CharField(max_length=20),
        ),
    ]
