# Generated by Django 4.0.4 on 2022-05-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_waitlist_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
                ('period_0', models.IntegerField()),
                ('period_1', models.IntegerField()),
                ('period_2', models.IntegerField()),
                ('period_3', models.IntegerField()),
                ('period_4', models.IntegerField()),
                ('period_5', models.IntegerField()),
                ('period_6', models.IntegerField()),
                ('period_7', models.IntegerField()),
                ('period_8', models.IntegerField()),
            ],
        ),
    ]
