# Generated by Django 4.1.1 on 2022-09-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendancerecord_reason_alter_incident_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='referral_url',
            field=models.URLField(default='hi'),
            preserve_default=False,
        ),
    ]
