# Generated by Django 4.1.1 on 2022-09-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_incident_referral_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(default='HELLO', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='referral_url',
            field=models.CharField(max_length=200),
        ),
    ]
