# Generated by Django 4.0.4 on 2022-05-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='period_0',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='period_1',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='period_2',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='period_3',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='period_4',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='period_5',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='period_6',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='period_7',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='period_8',
            field=models.TimeField(),
        ),
    ]
