# Generated by Django 4.0.4 on 2022-05-31 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_alter_schedule_period_0_alter_schedule_period_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
