# Generated by Django 4.1.1 on 2022-09-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_alter_incident_referral_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(default='9', max_length=2),
        ),
    ]
